name: Build updates.json (curl+jq, resilient)

on:
  schedule:
    - cron: "17 13 * * *"   # daily ~9:17am ET
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Fetch NYC Council (Legistar) -> matters.json
        run: |
          set +e
          echo "Requesting Legistar JSON..."
          # NOTE: use single quotes to avoid YAML/CI interpreting $ signs
          curl --fail -sS \
            -H 'accept: application/json' \
            'https://webapi.legistar.com/v1/nyc/Matters?$orderby=LastModifiedUtc%20desc&$top=50' \
            -o matters.json
          CURLCODE=$?
          echo "curl exit code: $CURLCODE"
          echo "First 200 chars of matters.json (if any):"
          head -c 200 matters.json || true
          echo
          # If curl failed or file missing, create empty JSON to keep pipeline alive
          if [ $CURLCODE -ne 0 ] || [ ! -s matters.json ]; then
            echo "[]"> matters.json
          fi
          # Validate JSON; if invalid, replace with []
          jq -e . matters.json >/dev/null 2>&1 || echo "[]" > matters.json
          echo "Validated matters.json size: $(wc -c < matters.json) bytes"

      - name: Build updates.json from matters.json
        run: |
          set +e
          # Build updates.json; if jq fails for any reason, write []
          jq '
            def lc: ascii_downcase;
            def keep(m): (
              [ m.MatterName, m.MatterTitle, m.MatterTypeName, m.MatterStatusName, m.MatterBodyName, m.MatterFile ]
              | map( ( . // "" ) | lc )
              | join(" ")
              | test("employment|labor|wage|salary|sick|safe|leave|retaliation|schedule|overtime")
            );
            [ .[] | select(keep(.)) |
              {
                id:      ("nycc-" + ( .MatterId | tostring )),
                source:  "NYC Council",
                title:   ( .MatterTitle // .MatterName // .MatterFile // "NYC Council matter" ),
                date:    ( .LastModifiedUtc // .MatterIntroDate // now | tostring ),
                url:     ( .MatterHyperlink // ("https://legistar.council.nyc.gov/LegislationDetail.aspx?ID=" + ( .MatterId | tostring )) ),
                tags:    ["NYC"]
              }
            ]
          ' matters.json > updates.json
          JQCODE=$?
          echo "jq build exit code: $JQCODE"
          if [ $JQCODE -ne 0 ] || [ ! -s updates.json ]; then
            echo "[]" > updates.json
          fi
          echo "Preview of updates.json:"
          head -n 40 updates.json || true

      - name: Commit updates.json if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add updates.json
            git commit -m "chore: update updates.json (resilient)"
            git push
          else
            echo "No changes to commit."
          fi
